spring:
  application:
    name: archivarius
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/test
    username: archi
    password: 123
  flyway:
    baseline-on-migrate: true
    check-location: false
app:
  soapToken: 'D468E929-A94E-4F16-A7D2-DB414EC53071'
  url: 'http://localhost:8081'
  soapUrl: 'https://cas-test.hostco.ru/RegUserService/services/RegUserService'
server:
  port: 8081