spring:
  application:
    name: archivarius
  datasource:
    driver-class-name: org.postgresql.Driver
    password: myservice1
    url: jdbc:postgresql://localhost:5432/test
    username: myservice1
server:
  port: 8081